FlattenMojo must not change DefaultModelBuilder as it is created once per session
FlattenMojo.profileInjector and FlattenMojo.profileSelector are then also used outside of Flatten-Mojos.

That prevents the property 'tools.jar' to be set accordingly during Maven initialize lifecycle, because the profile 'default-tools.jar' in com.sun.xml.ws:project:2.2.10 gets not activated.

The resulting error is as following:
[ERROR] 'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} @
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/xjc/api/ErrorListener
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	...